<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlayBook.Common\PlayBook.Common.csproj" />
    <ProjectReference Include="..\PlayBook.Data\PlayBook.Data.csproj" />
    <ProjectReference Include="..\PlayBook.Domain\PlayBook.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Pricing\" />
    <Folder Include="Helpers\" />
    <Folder Include="Utilities\" />
    <Folder Include="Validators\Interfaces\" />
    <Folder Include="Validators\Implementations\" />
  </ItemGroup>

</Project>
